---
namespace: community
name: odoo-role
version: 1.0.1
readme: README.md
authors:
  - Frazer SADO
description: Install odoo
license_file: COPYING
tags:
  - v1
repository: https://github.com/sadofrazer/frazer-odoo-role.git
documentation: https://github.com/sadofrazer/frazer-odoo-role.git
homepage: https://github.com/sadofrazer/frazer-odoo-role.git
issues: https://github.com/sadofrazer/frazer-odoo-role.git
build_ignore:
  - .gitignore
 